require('../transformationMatrix')
local inspect = require('../lib/inspect')

transMatrix = TransformationMatrix:new()
print(inspect(transMatrix.result))
transMatrix:translate(0, 800)
print("Translating...")
transMatrix:reflect_y()
print("Reflecting...")
print(inspect(transMatrix.result))
print(inspect(transMatrix:transform({{50}, {20}, {1}})))